/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 * Stub for CI builds. Real exports are generated by `npx convex codegen`.
 * This file is overwritten by codegen — do not edit manually.
 */
export const api: any = {};
export const internal: any = {};
export const components: any = {};
