/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 * Stub type for CI builds. Real types are generated by `npx convex codegen`.
 * This file is overwritten by codegen — do not edit manually.
 */
export type ComponentApi = any;
