/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 * Stub for CI builds. Real exports are generated by `npx convex codegen`.
 * This file is overwritten by codegen — do not edit manually.
 */
export const query: any = undefined;
export const mutation: any = undefined;
export const action: any = undefined;
export const internalMutation: any = undefined;
export const internalQuery: any = undefined;
export const internalAction: any = undefined;
