blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/V9yss7VfVT
    about: Ask questions and get help on Discord.
  - name: Website
    url: https://bntvllnt.com
    about: Visit bntvllnt.com for more info.
  - name: X / Twitter
    url: https://x.com/bntvllnt
    about: Follow @bntvllnt for updates.
